In [31]:
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 15 17:25:11 2019

@author: kinde
"""

import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing



top5000OverAllArtists = pd.read_csv("top5000_artist_overall_tfidf.csv", sep="\t")

In [77]:
top5000Gender = pd.read_csv("top5000_artist_gender_tfidf.csv", sep="\t")

   user_id  585  22804     15936  550  40662  28906  40631  699  52546  ...    \
0     3653  0.0    0.0  0.000000  0.0    0.0    0.0    0.0  0.0    0.0  ...
1     4813  0.0    0.0  0.000000  0.0    0.0    0.0    0.0  0.0    0.0  ...
2     5069  0.0    0.0  0.028264  0.0    0.0    0.0    0.0  0.0    0.0  ...
3  1000651  0.0    0.0  0.000000  0.0    0.0    0.0    0.0  0.0    0.0  ...
4  1004064  0.0    0.0  0.000000  0.0    0.0    0.0    0.0  0.0    0.0  ...

   43481  25329  17877  13087  38819  50464  27499  36553  3082  12497
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   0.0    0.0
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   0.0    0.0
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   0.0    0.0
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   0.0    0.0
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   0.0    0.0

[5 rows x 5001 columns]
   user_id       368      1602        54        55        27       283  \
0     3653  0.017031  0.022790  0.007277  0.000000  0.000000  0.000000
1     4813  0.043255  0.000000  0.000000  0.000000  0.000000  0.000000
2     5069  0.000000  0.025765  0.000000  0.000000  0.006109  0.007474
3  1000651  0.000000  0.030266  0.037238  0.043519  0.000000  0.000000
4  1004064  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

        320       135       153  ...    4416     20018  836     29471  91271  \
0  0.020329  0.032533  0.000000  ...     0.0  0.017681  0.0  0.000000    0.0
1  0.000000  0.000000  0.000000  ...     0.0  0.000000  0.0  0.000000    0.0
2  0.041436  0.000000  0.013014  ...     0.0  0.000000  0.0  0.032094    0.0
3  0.039817  0.000000  0.000000  ...     0.0  0.000000  0.0  0.000000    0.0
4  0.000000  0.000000  0.089769  ...     0.0  0.000000  0.0  0.000000    0.0

   12979  3466  7549  27525  57212
0    0.0   0.0   0.0    0.0    0.0
1    0.0   0.0   0.0    0.0    0.0
2    0.0   0.0   0.0    0.0    0.0
3    0.0   0.0   0.0    0.0    0.0
4    0.0   0.0   0.0    0.0    0.0

[5 rows x 5001 columns]

In [65]:
DropArtistOverAll = top5000OverAllArtists.drop('user_id', axis=1)
DropArtistGender = top5000Gender.drop('user_id', axis=1)

print(DropArtistOverAll.head(), DropArtistOverAll.shape)
print(DropArtistGender.head(), DropArtistGender.shape)

        368      1602        54        55        27       283       320  \
0  0.017031  0.022790  0.007277  0.000000  0.000000  0.000000  0.020329
1  0.043255  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
2  0.000000  0.025765  0.000000  0.000000  0.006109  0.007474  0.041436
3  0.000000  0.030266  0.037238  0.043519  0.000000  0.000000  0.039817
4  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

        135       153        16  ...    4416     20018  836     29471  91271  \
0  0.032533  0.000000  0.031439  ...     0.0  0.017681  0.0  0.000000    0.0
1  0.000000  0.000000  0.101614  ...     0.0  0.000000  0.0  0.000000    0.0
2  0.000000  0.013014  0.020548  ...     0.0  0.000000  0.0  0.032094    0.0
3  0.000000  0.000000  0.016891  ...     0.0  0.000000  0.0  0.000000    0.0
4  0.000000  0.089769  0.000000  ...     0.0  0.000000  0.0  0.000000    0.0

   12979  3466  7549  27525  57212
0    0.0   0.0   0.0    0.0    0.0
1    0.0   0.0   0.0    0.0    0.0
2    0.0   0.0   0.0    0.0    0.0
3    0.0   0.0   0.0    0.0    0.0
4    0.0   0.0   0.0    0.0    0.0

[5 rows x 5000 columns] (12180, 5000)
   3313  112188   15  29404  48440  34183  14225  50564  22804  34228  ...    \
0   0.0     0.0  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...
1   0.0     0.0  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...
2   0.0     0.0  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...
3   0.0     0.0  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...
4   0.0     0.0  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...

   204370  24483  53907  81139  38656  6800  641210  43398  4231  27052
0     0.0    0.0    0.0    0.0    0.0   0.0     0.0    0.0   0.0    0.0
1     0.0    0.0    0.0    0.0    0.0   0.0     0.0    0.0   0.0    0.0
2     0.0    0.0    0.0    0.0    0.0   0.0     0.0    0.0   0.0    0.0
3     0.0    0.0    0.0    0.0    0.0   0.0     0.0    0.0   0.0    0.0
4     0.0    0.0    0.0    0.0    0.0   0.0     0.0    0.0   0.0    0.0

[5 rows x 3750 columns] (12180, 3750)

In [66]:
#merging them:
result = pd.concat([DropArtistOverAll, DropArtistGender], axis=1, sort=False)
print(result.shape, result.head())

(12180, 8750)         368      1602        54        55        27       283       320  \
0  0.017031  0.022790  0.007277  0.000000  0.000000  0.000000  0.020329
1  0.043255  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
2  0.000000  0.025765  0.000000  0.000000  0.006109  0.007474  0.041436
3  0.000000  0.030266  0.037238  0.043519  0.000000  0.000000  0.039817
4  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

        135       153        16  ...    204370  24483  53907  81139  38656  \
0  0.032533  0.000000  0.031439  ...       0.0    0.0    0.0    0.0    0.0
1  0.000000  0.000000  0.101614  ...       0.0    0.0    0.0    0.0    0.0
2  0.000000  0.013014  0.020548  ...       0.0    0.0    0.0    0.0    0.0
3  0.000000  0.000000  0.016891  ...       0.0    0.0    0.0    0.0    0.0
4  0.000000  0.089769  0.000000  ...       0.0    0.0    0.0    0.0    0.0

   6800  641210  43398  4231  27052
0   0.0     0.0    0.0   0.0    0.0
1   0.0     0.0    0.0   0.0    0.0
2   0.0     0.0    0.0   0.0    0.0
3   0.0     0.0    0.0   0.0    0.0
4   0.0     0.0    0.0   0.0    0.0

[5 rows x 8750 columns]

In [67]:
#PCA of "result" DF:
from sklearn.decomposition import PCA
pca = PCA(n_components=450)
pca_result = pca.fit_transform(result)

print(pca_result)

[[ 2.37392492e-01 -2.62324732e-01 -5.72563210e-02 ... -3.98068169e-02
  -1.93348075e-02  3.93401524e-02]
 [ 8.49547095e-02 -1.42332704e-01  7.00074131e-03 ... -7.65574267e-03
  -8.34193185e-03 -2.15270398e-05]
 [ 3.48837764e-01 -2.50325316e-01 -1.66538168e-01 ... -4.50703016e-03
  -9.27321939e-03 -6.21045183e-03]
 ...
 [-1.68017642e-01  6.11675060e-02 -1.53225902e-02 ...  1.59747826e-02
   4.73851018e-06 -5.78691617e-03]
 [ 5.10769011e-02 -1.20170059e-01 -3.82556079e-02 ...  5.70705627e-02
  -3.96389804e-03  2.10851034e-02]
 [ 2.36919945e-02 -2.40336781e-02  9.67259931e-02 ...  1.27712101e-02
  -1.59627995e-02  2.55124815e-02]]

In [68]:
new_df_without_users = pd.DataFrame(data = pca_result)
print (new_df_without_users.head())

        0         1         2         3         4         5         6    \
0  0.237392 -0.262325 -0.057256 -0.072020 -0.019903 -0.044087  0.133188
1  0.084955 -0.142333  0.007001 -0.042193 -0.117109 -0.067958  0.026000
2  0.348838 -0.250325 -0.166538 -0.078491  0.374530 -0.043026 -0.042323
3  0.092308 -0.193349 -0.098305 -0.101135  0.161186 -0.009135 -0.111278
4 -0.249791 -0.022583  0.002492  0.030655  0.048478  0.053698 -0.070438

        7         8         9      ...          440       441       442  \
0 -0.101137  0.170562  0.016554    ...     0.000804  0.006610  0.013192
1 -0.025535 -0.009621  0.087305    ...    -0.042961  0.009445  0.025245
2 -0.034517 -0.079015 -0.036589    ...    -0.004352 -0.006286 -0.000424
3 -0.104230  0.083094 -0.071640    ...    -0.010812 -0.012378 -0.059323
4 -0.018161 -0.007604  0.179340    ...    -0.015487 -0.027563  0.041103

        443       444       445       446       447       448       449
0  0.009536  0.006019 -0.004407 -0.001573 -0.039807 -0.019335  0.039340
1  0.013421  0.018407  0.001581 -0.016531 -0.007656 -0.008342 -0.000022
2 -0.039440  0.029764 -0.035610 -0.018189 -0.004507 -0.009273 -0.006210
3 -0.027326  0.021738  0.012209 -0.000625  0.013505 -0.017007  0.004127
4 -0.051443  0.018721  0.025622  0.016202 -0.011538  0.030100  0.005171

[5 rows x 450 columns]

In [69]:
#adding the users:
new_df_without_users['user_id'] = top5000Gender['user_id'].values
print (new_df_without_users.head())

          0         1         2         3         4         5         6  \
0  0.237392 -0.262325 -0.057256 -0.072020 -0.019903 -0.044087  0.133188
1  0.084955 -0.142333  0.007001 -0.042193 -0.117109 -0.067958  0.026000
2  0.348838 -0.250325 -0.166538 -0.078491  0.374530 -0.043026 -0.042323
3  0.092308 -0.193349 -0.098305 -0.101135  0.161186 -0.009135 -0.111278
4 -0.249791 -0.022583  0.002492  0.030655  0.048478  0.053698 -0.070438

          7         8         9   ...          441       442       443  \
0 -0.101137  0.170562  0.016554   ...     0.006610  0.013192  0.009536
1 -0.025535 -0.009621  0.087305   ...     0.009445  0.025245  0.013421
2 -0.034517 -0.079015 -0.036589   ...    -0.006286 -0.000424 -0.039440
3 -0.104230  0.083094 -0.071640   ...    -0.012378 -0.059323 -0.027326
4 -0.018161 -0.007604  0.179340   ...    -0.027563  0.041103 -0.051443

        444       445       446       447       448       449  user_id
0  0.006019 -0.004407 -0.001573 -0.039807 -0.019335  0.039340     3653
1  0.018407  0.001581 -0.016531 -0.007656 -0.008342 -0.000022     4813
2  0.029764 -0.035610 -0.018189 -0.004507 -0.009273 -0.006210     5069
3  0.021738  0.012209 -0.000625  0.013505 -0.017007  0.004127  1000651
4  0.018721  0.025622  0.016202 -0.011538  0.030100  0.005171  1004064

[5 rows x 451 columns]

In [70]:
# now i need to add the user info
UserInfo = pd.read_csv("LFM-1b_subset_MTAP2018.csv", sep='\t')
UserInfo.columns =['user_id','age','gender','country']
merged_df = pd.merge(UserInfo, new_df_without_users, on='user_id')

print(new_df_without_users.shape)
print(merged_df.head(), new_df_without_users.shape)

(12180, 451)
    user_id  age gender country         0         1         2         3  \
0  49279959   28      f      ES  0.035889 -0.044412 -0.035833 -0.034161
1  46140219   26      m      US -0.012676 -0.075079 -0.057862 -0.117108
2  19262439   25      m      BR -0.281612 -0.103864  0.197560  0.012498
3   5974057   22      m      DE -0.137124  0.069263  0.099678  0.070941
4   8496608   23      m      RU  0.090769  0.174155  0.134268 -0.107821

          4         5    ...          440       441       442       443  \
0 -0.080406  0.011659    ...     0.008061 -0.008259  0.032360 -0.037601
1 -0.015682 -0.106149    ...    -0.003574 -0.014028  0.024796 -0.038243
2 -0.001510  0.181750    ...     0.047052 -0.024029 -0.000970  0.021035
3  0.039461 -0.037272    ...    -0.008761 -0.010103 -0.016918  0.024486
4 -0.014148 -0.035682    ...    -0.030259 -0.002430  0.039146  0.058776

        444       445       446       447       448       449
0 -0.002637  0.007043 -0.007900  0.002988  0.030545  0.025725
1  0.022566  0.000190  0.002662 -0.008541  0.005726 -0.028003
2  0.044710 -0.023723 -0.013942  0.037014 -0.002746  0.002874
3 -0.001870  0.019603 -0.025598 -0.011983  0.004196 -0.004610
4 -0.018194  0.015406  0.007910  0.005113 -0.027242 -0.058971

[5 rows x 454 columns] (12180, 451)

In [44]:
malesOnly = merged_df.loc[merged_df.gender == "m"][:2545]


females = merged_df.loc[merged_df.gender == "f"]

merged_df = pd.concat([malesOnly, females])
print(merged_df.head(), merged_df.shape)

    user_id  age gender country         0         1         2         3  \
1  46140219   26      m      US -0.015136 -0.075515 -0.060508 -0.115668
2  19262439   25      m      BR -0.284602 -0.099070  0.203987  0.007899
3   5974057   22      m      DE -0.140173  0.072285  0.092974  0.070379
4   8496608   23      m      RU  0.094885  0.185009  0.132657 -0.115188
6  37505807   21      m      IN -0.151974 -0.068637  0.050666  0.004580

          4         5    ...          440       441       442       443  \
1 -0.015617 -0.095385    ...     0.003653 -0.001789 -0.008180 -0.028768
2  0.006165  0.151634    ...    -0.027673  0.019500  0.007511 -0.007710
3  0.036361 -0.029086    ...     0.014992 -0.033547 -0.032971 -0.000122
4 -0.023229 -0.017386    ...     0.021334 -0.005411 -0.016873  0.039046
6 -0.042416 -0.025246    ...     0.001940 -0.028731 -0.016660  0.004592

        444       445       446       447       448       449
1  0.046513 -0.055994 -0.052450 -0.002273 -0.000416 -0.033529
2  0.022517  0.010146 -0.015753  0.048244  0.015468  0.011728
3 -0.026117  0.019539  0.031961  0.019590  0.001631  0.000781
4  0.039394 -0.004670 -0.011286  0.001730  0.029257  0.017248
6 -0.045470  0.026111 -0.027256 -0.012173 -0.025103  0.011618

[5 rows x 454 columns] (5090, 454)

In [75]:
#importing user stats and merging them:
user_stats = pd.read_csv("LFM-1b_users_additional.txt", sep='\t')
merged_df2 = pd.merge(merged_df, user_stats, on='user_id')

print(merged_df2.head(),merged_df2.shape)

    user_id  age gender country         0         1         2         3  \
0  49279959   28      f      ES  0.035889 -0.044412 -0.035833 -0.034161
1  46140219   26      m      US -0.012676 -0.075079 -0.057862 -0.117108
2  19262439   25      m      BR -0.281612 -0.103864  0.197560  0.012498
3   5974057   22      m      DE -0.137124  0.069263  0.099678  0.070941
4   8496608   23      m      RU  0.090769  0.174155  0.134268 -0.107821

          4         5           ...            relative_le_per_hour14  \
0 -0.080406  0.011659           ...                             0.033
1 -0.015682 -0.106149           ...                            0.0487
2 -0.001510  0.181750           ...                            0.0034
3  0.039461 -0.037272           ...                            0.0447
4 -0.014148 -0.035682           ...                            0.0721

   relative_le_per_hour15  relative_le_per_hour16  relative_le_per_hour17  \
0                  0.0422                  0.0367                  0.0239
1                  0.0572                  0.0723                  0.0487
2                   0.006                   0.016                  0.0338
3                  0.0474                  0.0548                  0.0562
4                  0.0678                   0.067                  0.0754

   relative_le_per_hour18  relative_le_per_hour19  relative_le_per_hour20  \
0                  0.0661                  0.0679                  0.1266
1                  0.0529                  0.0392                  0.0298
2                  0.0529                  0.0675                  0.0534
3                  0.0508                  0.0438                  0.0376
4                  0.0749                  0.0705                  0.0763

   relative_le_per_hour21  relative_le_per_hour22  relative_le_per_hour23
0                  0.1046                  0.0477                  0.0624
1                  0.0402                  0.0421                  0.0298
2                  0.0389                  0.0471                  0.0759
3                  0.0347                  0.0361                  0.0707
4                  0.0625                  0.0493                  0.0261

[5 rows x 496 columns] (12180, 496)

In [76]:
gendertempDF = merged_df2['age']
merged_df2 = merged_df2.drop('age', axis= 1)
#merged_df2 = merged_df2.drop('country', axis= 1)
merged_df2['age'] = gendertempDF.values
merged_df2 = merged_df2.drop('country', axis=1)
merged_df2 = merged_df2.drop('user_id', axis=1)
merged_df2 = merged_df2.drop('gender', axis=1)
merged_df2[:300].to_csv("AgeArtistPredictionTable.csv", sep=",", index = False)

'''
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
labelEncodedGender = le.fit_transform(merged_df2['gender'])
print(labelEncodedGender, len(labelEncodedGender))
merged_df2 = merged_df2.drop('gender', axis=1)
merged_df2['gender'] = labelEncodedGender
print(merged_df2)

merged_df2[:5000].to_csv("GenderArtistUnbalancedPredictionTable_short_LabelEncoded.csv", sep=",", index = False)
'''

'\nfrom sklearn import preprocessing\nle = preprocessing.LabelEncoder()\nlabelEncodedGender = le.fit_transform(merged_df2[\'gender\'])\nprint(labelEncodedGender, len(labelEncodedGender))\nmerged_df2 = merged_df2.drop(\'gender\', axis=1)\nmerged_df2[\'gender\'] = labelEncodedGender\nprint(merged_df2)\n\nmerged_df2[:5000].to_csv("GenderArtistUnbalancedPredictionTable_short_LabelEncoded.csv", sep=",", index = False)\n'